# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '4inputs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(10, 10, 781, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.title_label.setFont(font)
        self.title_label.setScaledContents(True)
        self.title_label.setObjectName("title_label")
        self.channel_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.channel_lineEdit.setGeometry(QtCore.QRect(30, 150, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.channel_lineEdit.setFont(font)
        self.channel_lineEdit.setClearButtonEnabled(False)
        self.channel_lineEdit.setObjectName("channel_lineEdit")
        self.cnt_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cnt_lineEdit.setGeometry(QtCore.QRect(30, 190, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cnt_lineEdit.setFont(font)
        self.cnt_lineEdit.setObjectName("cnt_lineEdit")
        self.dir_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dir_lineEdit.setGeometry(QtCore.QRect(30, 230, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dir_lineEdit.setFont(font)
        self.dir_lineEdit.setObjectName("dir_lineEdit")
        self.output_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_textBrowser.setGeometry(QtCore.QRect(415, 150, 371, 401))
        self.output_textBrowser.setObjectName("output_textBrowser")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(420, 120, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_label.setFont(font)
        self.output_label.setObjectName("output_label")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(30, 480, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setObjectName("start_pushButton")
        self.stop_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stop_pushButton.setGeometry(QtCore.QRect(260, 480, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stop_pushButton.setFont(font)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.frame_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.frame_lineEdit.setGeometry(QtCore.QRect(30, 270, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_lineEdit.setFont(font)
        self.frame_lineEdit.setText("")
        self.frame_lineEdit.setObjectName("frame_lineEdit")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(50, 350, 331, 91))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(":/image/colour_logo.png"))
        self.logo_label.setObjectName("logo_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">Videos to Frames</span></p></body></html>"))
        self.channel_lineEdit.setPlaceholderText(_translate("MainWindow", "Youtube에서 검색할 크리에이터 아이디 :"))
        self.cnt_lineEdit.setPlaceholderText(_translate("MainWindow", "수집할 영상 갯수 :"))
        self.dir_lineEdit.setPlaceholderText(_translate("MainWindow", "결과값을 저장할 경로"))
        self.output_label.setText(_translate("MainWindow", "상태창"))
        self.start_pushButton.setText(_translate("MainWindow", "실행"))
        self.stop_pushButton.setText(_translate("MainWindow", "종료"))
        self.frame_lineEdit.setPlaceholderText(_translate("MainWindow", "캡쳐 시간 간격 : ex) \"5초마다\" -> 5"))
import resource_rc
