# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\program.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(10, 10, 781, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.title_label.setFont(font)
        self.title_label.setScaledContents(True)
        self.title_label.setObjectName("title_label")
        self.channel_label = QtWidgets.QLabel(self.centralwidget)
        self.channel_label.setGeometry(QtCore.QRect(30, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.channel_label.setFont(font)
        self.channel_label.setObjectName("channel_label")
        self.cnt_label = QtWidgets.QLabel(self.centralwidget)
        self.cnt_label.setGeometry(QtCore.QRect(30, 180, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cnt_label.setFont(font)
        self.cnt_label.setObjectName("cnt_label")
        self.dir_label = QtWidgets.QLabel(self.centralwidget)
        self.dir_label.setGeometry(QtCore.QRect(30, 230, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.dir_label.setFont(font)
        self.dir_label.setObjectName("dir_label")
        self.channel_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.channel_lineEdit.setGeometry(QtCore.QRect(190, 130, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.channel_lineEdit.setFont(font)
        self.channel_lineEdit.setObjectName("channel_lineEdit")
        self.cnt_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cnt_lineEdit.setGeometry(QtCore.QRect(190, 180, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cnt_lineEdit.setFont(font)
        self.cnt_lineEdit.setObjectName("cnt_lineEdit")
        self.dir_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dir_lineEdit.setGeometry(QtCore.QRect(190, 230, 181, 20))
        self.dir_lineEdit.setObjectName("dir_lineEdit")
        self.output_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_textBrowser.setGeometry(QtCore.QRect(415, 150, 371, 401))
        self.output_textBrowser.setObjectName("output_textBrowser")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(420, 120, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_label.setFont(font)
        self.output_label.setObjectName("output_label")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(30, 480, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setObjectName("start_pushButton")
        self.stop_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stop_pushButton.setGeometry(QtCore.QRect(260, 480, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stop_pushButton.setFont(font)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(50, 310, 321, 131))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(":/image/colour_logo.png"))
        self.logo_label.setScaledContents(False)
        self.logo_label.setObjectName("logo_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.start_pushButton.clicked.connect(self.channel_input)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def channel_input(self):
        channel = self.channel_lineEdit.text()
        return channel

    def cnt_input(self):
        cnt = self.cnt_lineEdit.text()
        return cnt

    def dir_input(self):
        dir = self.dir_lineEdit.text()
        return dir

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">Videos to Frames</span></p></body></html>"))
        self.channel_label.setText(_translate("MainWindow", "크리에이터 아이디"))
        self.cnt_label.setText(_translate("MainWindow", "수집할 영상 갯수"))
        self.dir_label.setText(_translate("MainWindow", "저장할 폴더 경로"))
        self.output_label.setText(_translate("MainWindow", "상태창"))
        self.start_pushButton.setText(_translate("MainWindow", "실행"))
        self.stop_pushButton.setText(_translate("MainWindow", "종료"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
